
repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
    - id: codespell
      args:
        - --ignore-words-list=preformed

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: ^(gsw_check_data.h|gsw_saar_data.h)
